spring:
  datasource:
    url: jdbc:postgresql://ep-silent-wind-51875573-pooler.ap-southeast-1.aws.neon.tech/aj
    username: vvwv309
    password: pyJTG27LOYxB
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  admin-token: AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC
